-- product table --
CREATE TABLE product(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
fruit VARCHAR(255) NOT NULL,
`weight` VARCHAR(255) NOT NULL,
price VARCHAR(255) NOT NULL
);


CREATE TABLE category(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
category VARCHAR(255) NOT NULL
);

CREATE TABLE visitors(
id INT(11) AUTO_INCREMENT PRIMARY KEY,
ip_adress VARCHAR(255) NULL,
`language` VARCHAR(10) NOT NULL,
`time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP );
